### PR TITLE
add a basic package.json for NPM

### PR DESCRIPTION
**Pull request by zation**

### CODE REVIEW

**Comment by ardok** [comment]
Can we merge this?
Really want to use this library but this is the only alternative that I could find so far: https://www.npmjs.com/package/fixed-sticky

**Comment by zation** [comment]
@ardok for now, you can use `"ScrollToFixed": "zation/ScrollToFixed"` in your package.json

**Comment by bigspotteddog** [comment]
It is merged. Thank you very much!

**Comment by zation** [comment]
@bigspotteddog That's cool! Can you please make a publish to [NPM](https://www.npmjs.com/) so that everyone can use `npm install` to install this plugin

**Comment by bigspotteddog** [comment]
Here it is:
https://www.npmjs.com/package/scrolltofixed

**Comment by ardok** [comment]
Amazing. Thanks!

**Pull request merged**
